dist: bionic

#stages:
#  - Bash syntax verification
#  - installation test

#shellcheck:
#  stage: Bash syntax verification
sudo: required

services: [docker]

script:
  - sudo apt update
  - sudo apt install -y shellcheck

#installation:
#   stage: installation test
#   script:
#  - apt update && apt install -y sudo
  - cp install-freefem++.sh /tmp/
  - bash /tmp/install-freefem++.sh
#  - adduser user
#  - echo "user ALL=(root) NOPASSWD:ALL" >> /etc/sudoers
#  - su - user -c "bash /tmp/install-freefem++.sh"
